version: "3.8"

services:
  database:
    image: mongo
    restart: always
    container_name: database
    ports: 
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  app:
    container_name: app
    image: app
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_URL_DOCKER=mongodb://database:27017/api
    ports:
      - 3000:3000
    depends_on:
      - database
    
volumes:
  mongo_data:
  